In [1]:
import selenium
from selenium import webdriver
from selenium.webdriver.chrome.options import Options   #option-to copy the properties of chrome
from selenium.webdriver.common.by import By             #to access the properties of chrome
from selenium.webdriver.common.keys import Keys         #gives the connection b/w keyboard and browser
from webdriver_manager.chrome import ChromeDriverManager #
import pandas as pd

In [2]:
#define options and set browser capabilities
options=webdriver.ChromeOptions()

In [3]:
#Access browser capabilities
browser_name= options.to_capabilities()["browserName"]
print(browser_name)

chrome

In [4]:
#create WebDriver instance with options
driver=webdriver.Chrome(options=options)

In [5]:
#Navigate to a website
driver.get('https://www.myntra.com/')

In [6]:
search=driver.find_element(By.XPATH,".//input[@class='desktop-searchBar']")

In [7]:
search.send_keys("Smart Watches")

In [8]:
search.send_keys(Keys.ENTER)

In [9]:
brand=driver.find_elements(By.XPATH,".//h3[@class='product-brand']")
brands=[i.text for i in brand]
print(brands)

['CMF by Nothing', 'pebble', 'CMF by Nothing', 'boAt', 'pebble', 'NOISE', 'Titan', 'NOISE', 'Cultsport', 'NOISE', 'Fire-Boltt', 'NOISE', 'Fire-Boltt', 'Timex', 'NOISE', 'CMF by Nothing', 'boAt', 'Fire-Boltt', 'CMF by Nothing', 'JUST CORSECA', 'Fire-Boltt', 'Fastrack', 'NOISE', 'Fastrack', 'Fire-Boltt', 'Fire-Boltt', 'Realme', 'boAt', 'Fire-Boltt', 'Fastrack', 'Fire-Boltt', 'French Connection', 'NOISE', 'NOISE', 'Cultsport', 'Fire-Boltt', 'pebble', 'pebble', 'Fire-Boltt', 'NOISE', 'pebble', 'Fire-Boltt', 'HAMMER', 'boAt', 'NOISE', 'boAt', 'Fire-Boltt', 'boAt', 'NOISE', 'HAMMER']

In [10]:
prod=driver.find_elements(By.XPATH,".//h4[@class='product-product']")
products=[i.text for i in prod]
print(products)

['Watch Pro', 'Women 1.27" Smart Watch', 'Watch Pro', 'Unisex Wave Genesis Smartwatch', 'Women 1.27" Smart Watch', 'ColorFit Caliber Smartwatch', 'Smart 3 BT Calling SmartWatch', 'Fit Posh Smartwatch', 'Ace XR 1.43" Smart Watches', 'Mettle EliteEdition Smartwatch', 'Starlight Bluetooth Smartwatch', 'ColorFit Icon 2 Smartwatch', 'Hulk 1.78 inch Smartwatch', 'iConnect Gen+ Smart Watch', 'ColorFit Vision 3 Smartwatch', 'Watch Pro', 'Lunar Connect Ace', 'Hurricane Smartwatch', 'Watch Pro', 'Men Sprinter Pro Smartwatch', 'Supernova Bluetooth SmartWatch', 'FS2 BT Calling Smartwatch', 'Fit Posh Smartwatch', 'Z1 with HD Display Smartwatch', 'Cobra AMOLED Smart Watch', 'Hurricane Smartwatch', 'TechLife Watch S100', 'Storm Plus AMOLED Smart Watch', 'Visionary TWS Smartwatch', 'FS2 BT Calling Smartwatch', 'Eclipse Luxe 1.43" Amoled', 'Unisex Smart Watches', 'NoiseFit Evolve 3 Smartwatch', 'Fit Posh Smartwatch', 'Ace X Luxe 1.96" Smartwatch', 'Eclipse Luxe 1.43" Amoled', 'BT Calling Luxury Smartwatch', 'Hive 1.39" Display Smart Watch', 'Crusader Amoled 1.43BT Calling', 'ColorFit Vision 2 Smartwatch', 'Bold Pro Smart watches', 'Cobra AMOLED Smart Watch', 'Unisex Pulse 2.0 Smart Watch', 'Lunar Fit Smart Watch', 'Vision 2 Buzz Smartwatch', 'Lunar Fit Smart Watch', 'Hulk 1.78 inch Smartwatch', 'Unisex Wave Genesis Smartwatch', 'NoiseFit Evolve 4 Smartwatch', 'Bluetooth Calling Smart Watch']

In [11]:
price=driver.find_elements(By.XPATH,".//div[@class='product-price']")
prices=[i.text for i in price]
print(prices)

['Rs. 3499Rs. 5999(Rs. 2500 OFF)', 'Rs. 2299Rs. 6999(Rs. 4700 OFF)', 'Rs. 3499Rs. 5999(Rs. 2500 OFF)', 'Rs. 1899Rs. 6499(Rs. 4600 OFF)', 'Rs. 2299Rs. 6999(Rs. 4700 OFF)', 'Rs. 999Rs. 3999(Rs. 3000 OFF)', 'Rs. 4995Rs. 11995(Rs. 7000 OFF)', 'Rs. 1799Rs. 6999(Rs. 5200 OFF)', 'Rs. 2799Rs. 9999(72% OFF)', 'Rs. 1799Rs. 7999(Rs. 6200 OFF)', 'Rs. 1599Rs. 14999(Rs. 13400 OFF)', 'Rs. 1499Rs. 6999(Rs. 5500 OFF)', 'Rs. 1499Rs. 17999(Rs. 16500 OFF)', 'Rs. 2472Rs. 5495(55% OFF)', 'Rs. 2399Rs. 7999(Rs. 5600 OFF)', 'Rs. 3499Rs. 5999(Rs. 2500 OFF)', 'Rs. 2399Rs. 9499(Rs. 7100 OFF)', 'Rs. 1099Rs. 8999(Rs. 7900 OFF)', 'Rs. 3999Rs. 6499(Rs. 2500 OFF)', 'Rs. 8999', 'Rs. 1499Rs. 18999(Rs. 17500 OFF)', 'Rs. 1999Rs. 4995(Rs. 2996 OFF)', 'Rs. 1799Rs. 6999(Rs. 5200 OFF)', 'Rs. 1995Rs. 3995(Rs. 2000 OFF)', 'Rs. 1799Rs. 19999(Rs. 18200 OFF)', 'Rs. 1099Rs. 8999(Rs. 7900 OFF)', 'Rs. 2499Rs. 3999(Rs. 1500 OFF)', 'Rs. 2199Rs. 8999(Rs. 6800 OFF)', 'Rs. 1799Rs. 18499(Rs. 16700 OFF)', 'Rs. 1999Rs. 4995(Rs. 2996 OFF)', 'Rs. 1399Rs. 19999(Rs. 18600 OFF)', 'Rs. 1819Rs. 6999(74% OFF)', 'Rs. 1899Rs. 6999(Rs. 5100 OFF)', 'Rs. 1799Rs. 6999(Rs. 5200 OFF)', 'Rs. 3479Rs. 11999(71% OFF)', 'Rs. 1399Rs. 19999(Rs. 18600 OFF)', 'Rs. 1799Rs. 9999(Rs. 8200 OFF)', 'Rs. 1699Rs. 6499(Rs. 4800 OFF)', 'Rs. 1499Rs. 18999(Rs. 17500 OFF)', 'Rs. 1499Rs. 6999(Rs. 5500 OFF)', 'Rs. 3499Rs. 7499(Rs. 4000 OFF)', 'Rs. 1849Rs. 19999(Rs. 18150 OFF)', 'Rs. 1849Rs. 13330(Rs. 11481 OFF)', 'Rs. 2999Rs. 6990(Rs. 3991 OFF)', 'Rs. 1899Rs. 7999(Rs. 6100 OFF)', 'Rs. 2999Rs. 6990(Rs. 3991 OFF)', 'Rs. 1799Rs. 17999(Rs. 16200 OFF)', 'Rs. 1899Rs. 6499(Rs. 4600 OFF)', 'Rs. 4099Rs. 7999(Rs. 3900 OFF)', 'Rs. 1619Rs. 5999(73% OFF)']

In [12]:
df=pd.DataFrame(columns=['brands','products','prices'])
df

Empty DataFrame
Columns: [brands, products, prices]
Index: []

In [13]:
df

Empty DataFrame
Columns: [brands, products, prices]
Index: []

In [14]:
df['brands']=brands
df['products']=products
df['prices']=prices

In [15]:
df

,brands,products,prices
0,CMF by Nothing,Watch Pro,Rs. 3499Rs. 5999(Rs. 2500 OFF)
1,pebble,"Women 1.27"" Smart Watch",Rs. 2299Rs. 6999(Rs. 4700 OFF)
2,CMF by Nothing,Watch Pro,Rs. 3499Rs. 5999(Rs. 2500 OFF)
3,boAt,Unisex Wave Genesis Smartwatch,Rs. 1899Rs. 6499(Rs. 4600 OFF)
4,pebble,"Women 1.27"" Smart Watch",Rs. 2299Rs. 6999(Rs. 4700 OFF)
5,NOISE,ColorFit Caliber Smartwatch,Rs. 999Rs. 3999(Rs. 3000 OFF)
6,Titan,Smart 3 BT Calling SmartWatch,Rs. 4995Rs. 11995(Rs. 7000 OFF)
7,NOISE,Fit Posh Smartwatch,Rs. 1799Rs. 6999(Rs. 5200 OFF)
8,Cultsport,"Ace XR 1.43"" Smart Watches",Rs. 2799Rs. 9999(72% OFF)
9,NOISE,Mettle EliteEdition Smartwatch,Rs. 1799Rs. 7999(Rs. 6200 OFF)
10,Fire-Boltt,Starlight Bluetooth Smartwatch,Rs. 1599Rs. 14999(Rs. 13400 OFF)
11,NOISE,ColorFit Icon 2 Smartwatch,Rs. 1499Rs. 6999(Rs. 5500 OFF)
12,Fire-Boltt,Hulk 1.78 inch Smartwatch,Rs. 1499Rs. 17999(Rs. 16500 OFF)
13,Timex,iConnect Gen+ Smart Watch,Rs. 2472Rs. 5495(55% OFF)
14,NOISE,ColorFit Vision 3 Smartwatch,Rs. 2399Rs. 7999(Rs. 5600 OFF)
15,CMF by Nothing,Watch Pro,Rs. 3499Rs. 5999(Rs. 2500 OFF)
16,boAt,Lunar Connect Ace,Rs. 2399Rs. 9499(Rs. 7100 OFF)
17,Fire-Boltt,Hurricane Smartwatch,Rs. 1099Rs. 8999(Rs. 7900 OFF)
18,CMF by Nothing,Watch Pro,Rs. 3999Rs. 6499(Rs. 2500 OFF)
19,JUST CORSECA,Men Sprinter Pro Smartwatch,Rs. 8999
20,Fire-Boltt,Supernova Bluetooth SmartWatch,Rs. 1499Rs. 18999(Rs. 17500 OFF)
21,Fastrack,FS2 BT Calling Smartwatch,Rs. 1999Rs. 4995(Rs. 2996 OFF)
22,NOISE,Fit Posh Smartwatch,Rs. 1799Rs. 6999(Rs. 5200 OFF)
23,Fastrack,Z1 with HD Display Smartwatch,Rs. 1995Rs. 3995(Rs. 2000 OFF)
24,Fire-Boltt,Cobra AMOLED Smart Watch,Rs. 1799Rs. 19999(Rs. 18200 OFF)
25,Fire-Boltt,Hurricane Smartwatch,Rs. 1099Rs. 8999(Rs. 7900 OFF)
26,Realme,TechLife Watch S100,Rs. 2499Rs. 3999(Rs. 1500 OFF)
27,boAt,Storm Plus AMOLED Smart Watch,Rs. 2199Rs. 8999(Rs. 6800 OFF)
28,Fire-Boltt,Visionary TWS Smartwatch,Rs. 1799Rs. 18499(Rs. 16700 OFF)
29,Fastrack,FS2 BT Calling Smartwatch,Rs. 1999Rs. 4995(Rs. 2996 OFF)
30,Fire-Boltt,"Eclipse Luxe 1.43"" Amoled",Rs. 1399Rs. 19999(Rs. 18600 OFF)
31,French Connection,Unisex Smart Watches,Rs. 1819Rs. 6999(74% OFF)
32,NOISE,NoiseFit Evolve 3 Smartwatch,Rs. 1899Rs. 6999(Rs. 5100 OFF)
33,NOISE,Fit Posh Smartwatch,Rs. 1799Rs. 6999(Rs. 5200 OFF)
34,Cultsport,"Ace X Luxe 1.96"" Smartwatch",Rs. 3479Rs. 11999(71% OFF)
35,Fire-Boltt,"Eclipse Luxe 1.43"" Amoled",Rs. 1399Rs. 19999(Rs. 18600 OFF)
36,pebble,BT Calling Luxury Smartwatch,Rs. 1799Rs. 9999(Rs. 8200 OFF)
37,pebble,"Hive 1.39"" Display Smart Watch",Rs. 1699Rs. 6499(Rs. 4800 OFF)
38,Fire-Boltt,Crusader Amoled 1.43BT Calling,Rs. 1499Rs. 18999(Rs. 17500 OFF)
39,NOISE,ColorFit Vision 2 Smartwatch,Rs. 1499Rs. 6999(Rs. 5500 OFF)
40,pebble,Bold Pro Smart watches,Rs. 3499Rs. 7499(Rs. 4000 OFF)
41,Fire-Boltt,Cobra AMOLED Smart Watch,Rs. 1849Rs. 19999(Rs. 18150 OFF)
42,HAMMER,Unisex Pulse 2.0 Smart Watch,Rs. 1849Rs. 13330(Rs. 11481 OFF)
43,boAt,Lunar Fit Smart Watch,Rs. 2999Rs. 6990(Rs. 3991 OFF)
44,NOISE,Vision 2 Buzz Smartwatch,Rs. 1899Rs. 7999(Rs. 6100 OFF)
45,boAt,Lunar Fit Smart Watch,Rs. 2999Rs. 6990(Rs. 3991 OFF)
46,Fire-Boltt,Hulk 1.78 inch Smartwatch,Rs. 1799Rs. 17999(Rs. 16200 OFF)
47,boAt,Unisex Wave Genesis Smartwatch,Rs. 1899Rs. 6499(Rs. 4600 OFF)
48,NOISE,NoiseFit Evolve 4 Smartwatch,Rs. 4099Rs. 7999(Rs. 3900 OFF)
49,HAMMER,Bluetooth Calling Smart Watch,Rs. 1619Rs. 5999(73% OFF)

In [16]:
df.to_csv("SmartWatches.csv")